spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sab
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    com.baomidou.mybatisplus: debug



